### ISSUE TITLE
Is it possible to add full path to file in "location" attribute added by base formatter?

### ISSUE THREAD

**Issue by shubik** [yyyar/loginator#1]
https://github.com/yyyar/loginator/blob/master/lib/formatters/_base.js -- ideally "location" shows full path, otherwise it usually shows something like "index.js"

**Comment by yyyar** [comment]
Actually, you can use `%location` to print only filename and line number, or `%longlocation` for full file path and line number. It's described in the README in formatters section.
Does it help?

**Comment by shubik** [comment]
@charliemantle fyi
@yyyar yes it helps, thanks. If long location was default, it would be quite nice ))
